name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - flutterflow

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the flutterflow branch
        uses: actions/checkout@v3
        with:
          ref: flutterflow
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --web-renderer html

      - name: Checkout the main branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout main
          git pull origin main

      - name: Clear existing files
        run: |
          find . -maxdepth 1 ! -name '.git' ! -name '.' -exec rm -rf {} +

      - name: Copy build/web to root
        run: cp -r build/web/* .

      - name: Commit and push to main
        run: |
          git add .
          git commit -m "Deploy Flutter Web build from flutterflow branch" || echo "No changes to commit"
          git push origin main
