name: Build and Deploy Flutter Web
 
on:
  push:
    branches:
      - flutterflow  # Adjust this to the branch you want to use
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Set up Flutter
      uses: subosito/flutter-action@v2.5.0
      with:
        flutter-version: '3.27.3'  # Replace with your desired Flutter version
 
    - name: Install dependencies
      run: flutter pub get
 
    - name: Build Flutter Web
      run: flutter build web --release
