name: Build Flutter Web and Save to Folder

on:
  push:
    branches:
      - flutterflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --web-renderer canvaskit --release

      - name: Copy build to build_web/
        run: |
          rm -rf build_web
          mkdir build_web
          cp -r build/web/* build_web/

      - name: Create Dockerfile and nginx.conf
        run: |
          echo "FROM nginx:alpine
          COPY build_web/ /usr/share/nginx/html
          COPY nginx.conf /etc/nginx/conf.d/default.conf" > Dockerfile

          echo "server {
            listen 80;
            server_name localhost;

            root /usr/share/nginx/html;
            index index.html;

            location / {
              try_files \$uri \$uri/ /index.html;
            }
          }" > nginx.conf

      - name: Commit and push build_web + Dockerfile
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add build_web Dockerfile nginx.conf
          git commit -m "Atualiza build_web e arquivos de deploy"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger deploy on EasyPanel
        run: curl -X POST ${{ secrets.EASYPANEL_WEBHOOK_URL }}
