name: Build Flutter Web and Save to Folder

on:
  push:
    branches:
      - flutterflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --web-renderer html --release

      - name: Copy build to build_web/
        run: |
          rm -rf build_web
          mkdir build_web
          cp -r build/web/* build_web/

      - name: Commit and push build_web
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add build_web
          git commit -m "Atualiza pasta build_web com novo build"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
